# Generated by Django 3.1.1 on 2020-10-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='cover',
            field=models.ImageField(default='ss', upload_to='profilePics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='taher', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='hh', upload_to='profilePics'),
            preserve_default=False,
        ),
    ]
