# Generated by Django 3.1.1 on 2020-10-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
