# Generated by Django 3.1.1 on 2020-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201002_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cover',
            field=models.ImageField(default='1.jpg', upload_to='profilePics'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='profilePics'),
        ),
    ]
