# Generated by Django 3.1.1 on 2020-10-08 15:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_member_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='media/circlepics')),
                ('cover', models.ImageField(upload_to='media/circlepics')),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', users.models.MemberManager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='cover',
            field=models.ImageField(default='1.jpg', upload_to='media/profile_pics'),
        ),
    ]
