# Generated by Django 3.1.1 on 2020-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201006_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cover',
            field=models.ImageField(default='1.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='media'),
        ),
    ]
