# Generated by Django 3.1.1 on 2020-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201008_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='circle_type',
            field=models.CharField(choices=[('teah', 'tech'), ('non-tech', 'non-tech')], default='tech', max_length=10),
            preserve_default=False,
        ),
    ]
