# Generated by Django 3.1.1 on 2020-10-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_circle_circle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='circle_type',
        ),
    ]
