# Generated by Django 3.1.1 on 2020-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcard',
            old_name='tasks',
            new_name='num',
        ),
    ]
